import jsPDF from 'jspdf'
import type { AnalysisResult } from './api'

// ── Design tokens ────────────────────────────────────────────
const C = {
  bg:        [11, 13, 26]   as [number,number,number],
  surface:   [18, 20, 38]   as [number,number,number],
  border:    [40, 44, 80]   as [number,number,number],
  accent:    [99, 102, 241] as [number,number,number],
  accentSoft:[60, 63, 160]  as [number,number,number],
  white:     [250, 250, 250] as [number,number,number],
  muted:     [140, 140, 170] as [number,number,number],
  success:   [34, 197, 94]  as [number,number,number],
  warning:   [251, 191, 36] as [number,number,number],
  negative:  [239, 68, 68]  as [number,number,number],
}

const PAGE_W = 210
const PAGE_H = 297
const ML = 18   // margin left
const MR = 18   // margin right
const CW = PAGE_W - ML - MR  // content width

function sentimentColor(label: string): [number,number,number] {
  const l = label.toLowerCase()
  if (l === 'positive') return C.success
  if (l === 'negative') return C.negative
  return C.muted
}

export function generatePDFReport(result: AnalysisResult, fileName: string): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })

  let y = 0  // current Y cursor

  // ── helpers ──────────────────────────────────────────────

  function newPage() {
    doc.addPage()
    y = 0
    drawPageBg()
    drawPageFooter()
  }

  function checkY(needed: number) {
    if (y + needed > PAGE_H - 22) newPage()
  }

  function drawPageBg() {
    doc.setFillColor(...C.bg)
    doc.rect(0, 0, PAGE_W, PAGE_H, 'F')
  }

  function drawPageFooter() {
    const pageNum = doc.getNumberOfPages()
    doc.setFillColor(...C.surface)
    doc.rect(0, PAGE_H - 12, PAGE_W, 12, 'F')
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.3)
    doc.line(0, PAGE_H - 12, PAGE_W, PAGE_H - 12)
    doc.setFontSize(7.5)
    doc.setTextColor(...C.muted)
    doc.text('Generated by Doclyze · AI Document Intelligence', ML, PAGE_H - 4.5)
    doc.text(`Page ${pageNum}`, PAGE_W - MR, PAGE_H - 4.5, { align: 'right' })
  }

  function sectionCard(cardY: number, cardH: number) {
    doc.setFillColor(...C.surface)
    doc.roundedRect(ML, cardY, CW, cardH, 2.5, 2.5, 'F')
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.25)
    doc.roundedRect(ML, cardY, CW, cardH, 2.5, 2.5, 'S')
  }

  function accentBar(barY: number, barH: number) {
    doc.setFillColor(...C.accent)
    doc.roundedRect(ML, barY, 2.5, barH, 1, 1, 'F')
  }

  function sectionTitle(title: string, titleY: number) {
    doc.setFontSize(9)
    doc.setTextColor(...C.muted)
    doc.setFont('helvetica', 'bold')
    const upper = title.toUpperCase()
    doc.text(upper, ML + 6, titleY)
    // underline
    const tw = doc.getTextWidth(upper)
    doc.setDrawColor(...C.accentSoft)
    doc.setLineWidth(0.3)
    doc.line(ML + 6, titleY + 1, ML + 6 + tw, titleY + 1)
  }

  function tag(text: string, tx: number, ty: number, color: [number,number,number] = C.accent): number {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    const tw = doc.getTextWidth(text) + 5
    doc.setFillColor(color[0], color[1], color[2], 0.15)
    doc.roundedRect(tx, ty - 3.5, tw, 5.5, 1.5, 1.5, 'F')
    doc.setDrawColor(color[0], color[1], color[2])
    doc.setLineWidth(0.2)
    doc.roundedRect(tx, ty - 3.5, tw, 5.5, 1.5, 1.5, 'S')
    doc.setTextColor(...color)
    doc.text(text, tx + 2.5, ty)
    return tw + 2  // gap after tag
  }

  function entityRow(label: string, items: string[], rowY: number): number {
    if (!items || items.length === 0) return rowY
    checkY(16)
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.muted)
    doc.text(label, ML + 6, rowY)
    rowY += 5

    let tx = ML + 6
    let lineY = rowY
    const maxX = ML + CW - 4

    for (const item of items.slice(0, 20)) {
      const tw = doc.getTextWidth(item) + 7
      if (tx + tw > maxX) {
        tx = ML + 6
        lineY += 7
        checkY(7)
      }
      tag(item, tx, lineY)
      tx += tw
    }
    return lineY + 8
  }

  // ── Page 1 background ────────────────────────────────────
  drawPageBg()
  drawPageFooter()

  // ── HEADER BAND ──────────────────────────────────────────
  doc.setFillColor(...C.surface)
  doc.rect(0, 0, PAGE_W, 42, 'F')
  doc.setFillColor(...C.accent)
  doc.rect(0, 0, 4, 42, 'F')
  doc.setDrawColor(...C.border)
  doc.setLineWidth(0.3)
  doc.line(0, 42, PAGE_W, 42)

  // Doclyze wordmark
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Doclyze', 12, 16)

  // Tagline
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text('AI Document Intelligence', 12, 22)

  // Report title (right side)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Document Analysis Report', PAGE_W - MR, 14, { align: 'right' })

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text(`${dateStr}  ·  ${timeStr}`, PAGE_W - MR, 20, { align: 'right' })

  // File info row
  doc.setFontSize(8.5)
  doc.setTextColor(...C.muted)
  doc.text(`File: `, 12, 33)
  doc.setTextColor(...C.white)
  doc.text(fileName || result.fileName || 'Unknown', 12 + doc.getTextWidth('File: '), 33)

  doc.setTextColor(...C.muted)
  doc.text(`Type: `, 90, 33)
  doc.setTextColor(...C.accent)
  doc.text((result.document_type || 'general').toUpperCase(), 90 + doc.getTextWidth('Type: '), 33)

  y = 52

  // ── PROCESSING INSIGHTS ──────────────────────────────────
  const insightRows: Array<[string, string]> = []
  if (result.fileSize > 0) insightRows.push(['File Size', (result.fileSize / 1024).toFixed(1) + ' KB'])
  if (result.metadata?.processing_time_ms > 0) insightRows.push(['Processing Time', (result.metadata.processing_time_ms / 1000).toFixed(1) + ' s'])
  insightRows.push(['OCR Engine', result.metadata?.ocr_used ? (result.metadata.ocr_engine === 'vision' ? 'Google Vision' : result.metadata.ocr_engine || 'OCR') : 'Not Used'])
  if (result.confidence > 0) insightRows.push(['Confidence', Math.round(result.confidence * 100) + '%'])

  const insightH = 10 + insightRows.length * 6.5
  sectionCard(y, insightH)
  accentBar(y + 3, insightH - 6)
  sectionTitle('Processing Insights', y + 7)
  let iy = y + 13
  for (const [k, v] of insightRows) {
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.muted)
    doc.text(k, ML + 6, iy)
    doc.setTextColor(...C.white)
    doc.text(v, ML + CW - 4, iy, { align: 'right' })
    iy += 6.5
  }
  y += insightH + 6

  // ── SENTIMENT ────────────────────────────────────────────
  const sentLabel = typeof result.sentiment === 'string'
    ? result.sentiment
    : result.sentiment?.label || 'Neutral'
  const sentConf = typeof result.sentiment === 'object' && result.sentiment?.confidence
    ? Math.round(result.sentiment.confidence * 100) + '%'
    : ''

  checkY(22)
  sectionCard(y, 22)
  accentBar(y + 3, 16)
  sectionTitle('Sentiment', y + 7)
  const sColor = sentimentColor(sentLabel)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...sColor)
  doc.text(sentLabel.charAt(0).toUpperCase() + sentLabel.slice(1).toLowerCase(), ML + 6, y + 16)
  if (sentConf) {
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.muted)
    doc.text(`Confidence: ${sentConf}`, ML + CW - 4, y + 16, { align: 'right' })
  }
  y += 28

  // ── SUMMARY ──────────────────────────────────────────────
  if (result.summary && result.summary.length > 10) {
    const summaryLines = doc.splitTextToSize(result.summary, CW - 12)
    const summaryH = 14 + summaryLines.length * 5.5
    checkY(summaryH)
    sectionCard(y, summaryH)
    accentBar(y + 3, summaryH - 6)
    sectionTitle('AI Generated Summary', y + 7)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.white)
    doc.text(summaryLines, ML + 6, y + 13)
    y += summaryH + 6
  }

  // ── ENTITIES ─────────────────────────────────────────────
  const ent = result.entities || {}
  const entitySections: Array<[string, string[]]> = [
    ['Persons / Names',    ent.persons || []],
    ['Organizations',      ent.organizations || []],
    ['Locations',          ent.locations || []],
    ['Dates',              ent.dates || []],
    ['Monetary Amounts',   ent.monetary_amounts || []],
    ['Skills',             ent.skills || []],
    ['Projects',           ent.projects || []],
    ['Emails',             ent.emails || []],
    ['Phone Numbers',      ent.phone_numbers || []],
    ['URLs',               ent.urls || []],
    ['Invoice Numbers',    ent.invoice_numbers || []],
  ].filter(([, items]) => Array.isArray(items) && items.length > 0) as Array<[string, string[]]>

  if (entitySections.length > 0) {
    // Estimate total height for the entity card
    let totalEntityH = 14
    for (const [, items] of entitySections) {
      const rows = Math.ceil(items.slice(0, 20).length / 5)
      totalEntityH += 5 + rows * 7 + 4
    }
    totalEntityH = Math.min(totalEntityH, PAGE_H - y - 30)

    checkY(20)
    const cardStartY = y
    sectionCard(cardStartY, 12)  // header only first
    accentBar(cardStartY + 3, 9)
    sectionTitle('Extracted Entities', cardStartY + 7)
    y = cardStartY + 14

    for (const [label, items] of entitySections) {
      checkY(16)
      y = entityRow(label, items, y)
    }

    // Draw the card border around all entity content
    const entityCardH = y - cardStartY + 2
    doc.setFillColor(...C.surface)
    doc.roundedRect(ML, cardStartY, CW, entityCardH, 2.5, 2.5, 'F')
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.25)
    doc.roundedRect(ML, cardStartY, CW, entityCardH, 2.5, 2.5, 'S')
    accentBar(cardStartY + 3, entityCardH - 6)
    sectionTitle('Extracted Entities', cardStartY + 7)
    y = cardStartY + 14
    for (const [label, items] of entitySections) {
      y = entityRow(label, items, y)
    }
    y += 4
  } else {
    checkY(18)
    sectionCard(y, 18)
    accentBar(y + 3, 12)
    sectionTitle('Extracted Entities', y + 7)
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(...C.muted)
    doc.text('No structured entities detected in this document.', ML + 6, y + 14)
    y += 24
  }

  // ── Save ─────────────────────────────────────────────────
  const safeName = (fileName || result.fileName || 'report').replace(/\.[^.]+$/, '').replace(/[^a-z0-9_\-]/gi, '_')
  doc.save(`${safeName}_doclyze_report.pdf`)
}
